// MammoAssist Mock Data - Simulated for demonstration only

import { Case, Finding, AuditEvent, Decision } from './types';

// Generate 30 simulated cases with varied characteristics
export const mockCases: Case[] = [
  // High risk cases (riskScore > 75)
  {
    id: 'CASE-001',
    createdAt: '2025-12-15T08:30:00Z',
    status: 'pending',
    riskScore: 92,
    confidence: 0.87,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-84729',
    modality: 'tomosynthesis',
    notes: 'Irregular mass with spiculated margins',
    ageBand: '60-69',
    deviceType: 'vendor-a',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'malignant',
  },
  {
    id: 'CASE-002',
    createdAt: '2025-12-15T09:15:00Z',
    status: 'in-review',
    riskScore: 88,
    confidence: 0.76,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-93251',
    modality: 'mammogram',
    notes: 'Architectural distortion upper outer quadrant',
    ageBand: '70+',
    deviceType: 'vendor-b',
    densityCategory: 'd-dense',
    groundTruth: 'malignant',
  },
  {
    id: 'CASE-003',
    createdAt: '2025-12-15T10:00:00Z',
    status: 'pending',
    riskScore: 81,
    confidence: 0.52,
    uncertaintyFlag: true,
    patientMaskedId: 'PT-15837',
    modality: 'mammogram',
    notes: 'Suspicious calcifications, uncertain pattern',
    ageBand: '50-59',
    deviceType: 'vendor-a',
    densityCategory: 'd-dense',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-004',
    createdAt: '2025-12-15T11:20:00Z',
    status: 'needs-second-review',
    riskScore: 79,
    confidence: 0.48,
    uncertaintyFlag: true,
    patientMaskedId: 'PT-62491',
    modality: 'tomosynthesis',
    notes: 'Asymmetry, low confidence assessment',
    ageBand: '40-49',
    deviceType: 'vendor-c',
    densityCategory: 'b-scattered',
    groundTruth: 'benign',
  },
  
  // Medium risk cases (50-75)
  {
    id: 'CASE-005',
    createdAt: '2025-12-15T13:45:00Z',
    status: 'pending',
    riskScore: 68,
    confidence: 0.82,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-74529',
    modality: 'mammogram',
    notes: 'Focal asymmetry, likely benign',
    ageBand: '50-59',
    deviceType: 'vendor-b',
    densityCategory: 'b-scattered',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-006',
    createdAt: '2025-12-15T14:10:00Z',
    status: 'in-review',
    riskScore: 72,
    confidence: 0.79,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-39462',
    modality: 'tomosynthesis',
    notes: 'Small mass with circumscribed margins',
    ageBand: '60-69',
    deviceType: 'vendor-a',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-007',
    createdAt: '2025-12-15T15:30:00Z',
    status: 'pending',
    riskScore: 64,
    confidence: 0.54,
    uncertaintyFlag: true,
    patientMaskedId: 'PT-58271',
    modality: 'mammogram',
    notes: 'Subtle density change, uncertain significance',
    ageBand: '70+',
    deviceType: 'vendor-c',
    densityCategory: 'a-fatty',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-008',
    createdAt: '2025-12-16T08:00:00Z',
    status: 'pending',
    riskScore: 58,
    confidence: 0.71,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-84153',
    modality: 'mammogram',
    notes: 'Scattered benign calcifications',
    ageBand: '50-59',
    deviceType: 'vendor-b',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-009',
    createdAt: '2025-12-16T08:30:00Z',
    status: 'finalized',
    riskScore: 62,
    confidence: 0.85,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-29384',
    modality: 'tomosynthesis',
    notes: 'Stable fibroadenoma',
    ageBand: '40-49',
    deviceType: 'vendor-a',
    densityCategory: 'b-scattered',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-010',
    createdAt: '2025-12-16T09:15:00Z',
    status: 'pending',
    riskScore: 55,
    confidence: 0.68,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-67428',
    modality: 'mammogram',
    notes: 'Normal breast parenchyma',
    ageBand: '60-69',
    deviceType: 'vendor-b',
    densityCategory: 'a-fatty',
    groundTruth: 'benign',
  },

  // Low risk cases (< 50)
  {
    id: 'CASE-011',
    createdAt: '2025-12-16T10:00:00Z',
    status: 'finalized',
    riskScore: 18,
    confidence: 0.95,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-12948',
    modality: 'mammogram',
    notes: 'Normal study, no significant findings',
    ageBand: '40-49',
    deviceType: 'vendor-a',
    densityCategory: 'a-fatty',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-012',
    createdAt: '2025-12-16T10:30:00Z',
    status: 'pending',
    riskScore: 42,
    confidence: 0.89,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-58394',
    modality: 'tomosynthesis',
    notes: 'Benign intramammary lymph node',
    ageBand: '50-59',
    deviceType: 'vendor-c',
    densityCategory: 'b-scattered',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-013',
    createdAt: '2025-12-16T11:00:00Z',
    status: 'finalized',
    riskScore: 35,
    confidence: 0.92,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-74251',
    modality: 'mammogram',
    notes: 'Oil cyst, benign finding',
    ageBand: '60-69',
    deviceType: 'vendor-b',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-014',
    createdAt: '2025-12-16T11:45:00Z',
    status: 'pending',
    riskScore: 28,
    confidence: 0.88,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-39571',
    modality: 'mammogram',
    notes: 'Normal dense breast tissue',
    ageBand: '40-49',
    deviceType: 'vendor-a',
    densityCategory: 'd-dense',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-015',
    createdAt: '2025-12-16T12:15:00Z',
    status: 'in-review',
    riskScore: 45,
    confidence: 0.51,
    uncertaintyFlag: true,
    patientMaskedId: 'PT-82649',
    modality: 'tomosynthesis',
    notes: 'Questionable finding, low confidence',
    ageBand: '70+',
    deviceType: 'vendor-c',
    densityCategory: 'b-scattered',
    groundTruth: 'benign',
  },

  // Additional diverse cases
  {
    id: 'CASE-016',
    createdAt: '2025-12-16T13:00:00Z',
    status: 'pending',
    riskScore: 76,
    confidence: 0.73,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-51937',
    modality: 'mammogram',
    notes: 'Irregular mass, recommend biopsy',
    ageBand: '60-69',
    deviceType: 'vendor-a',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'malignant',
  },
  {
    id: 'CASE-017',
    createdAt: '2025-12-16T13:30:00Z',
    status: 'pending',
    riskScore: 21,
    confidence: 0.94,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-68324',
    modality: 'tomosynthesis',
    notes: 'Completely normal examination',
    ageBand: '40-49',
    deviceType: 'vendor-b',
    densityCategory: 'a-fatty',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-018',
    createdAt: '2025-12-16T14:00:00Z',
    status: 'needs-second-review',
    riskScore: 69,
    confidence: 0.49,
    uncertaintyFlag: true,
    patientMaskedId: 'PT-93746',
    modality: 'mammogram',
    notes: 'Ambiguous finding in dense tissue',
    ageBand: '50-59',
    deviceType: 'vendor-c',
    densityCategory: 'd-dense',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-019',
    createdAt: '2025-12-16T14:30:00Z',
    status: 'finalized',
    riskScore: 84,
    confidence: 0.81,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-27518',
    modality: 'tomosynthesis',
    notes: 'Confirmed malignancy, referred for treatment',
    ageBand: '70+',
    deviceType: 'vendor-a',
    densityCategory: 'b-scattered',
    groundTruth: 'malignant',
  },
  {
    id: 'CASE-020',
    createdAt: '2025-12-16T15:00:00Z',
    status: 'pending',
    riskScore: 52,
    confidence: 0.77,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-46281',
    modality: 'mammogram',
    notes: 'Benign-appearing calcifications',
    ageBand: '50-59',
    deviceType: 'vendor-b',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'benign',
  },

  // Cases 21-30 for more data
  {
    id: 'CASE-021',
    createdAt: '2025-12-14T08:00:00Z',
    status: 'finalized',
    riskScore: 15,
    confidence: 0.96,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-13579',
    modality: 'mammogram',
    notes: 'Routine screening, negative',
    ageBand: '40-49',
    deviceType: 'vendor-a',
    densityCategory: 'a-fatty',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-022',
    createdAt: '2025-12-14T09:00:00Z',
    status: 'finalized',
    riskScore: 38,
    confidence: 0.86,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-24680',
    modality: 'tomosynthesis',
    notes: 'Benign simple cyst',
    ageBand: '60-69',
    deviceType: 'vendor-b',
    densityCategory: 'b-scattered',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-023',
    createdAt: '2025-12-14T10:00:00Z',
    status: 'pending',
    riskScore: 74,
    confidence: 0.69,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-35791',
    modality: 'mammogram',
    notes: 'Suspicious microcalcifications',
    ageBand: '70+',
    deviceType: 'vendor-c',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'malignant',
  },
  {
    id: 'CASE-024',
    createdAt: '2025-12-14T11:00:00Z',
    status: 'in-review',
    riskScore: 61,
    confidence: 0.75,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-46802',
    modality: 'tomosynthesis',
    notes: 'Asymmetric density, probably benign',
    ageBand: '50-59',
    deviceType: 'vendor-a',
    densityCategory: 'd-dense',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-025',
    createdAt: '2025-12-14T13:00:00Z',
    status: 'pending',
    riskScore: 89,
    confidence: 0.84,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-57913',
    modality: 'mammogram',
    notes: 'High suspicion for malignancy',
    ageBand: '60-69',
    deviceType: 'vendor-b',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'malignant',
  },
  {
    id: 'CASE-026',
    createdAt: '2025-12-14T14:00:00Z',
    status: 'finalized',
    riskScore: 24,
    confidence: 0.91,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-68024',
    modality: 'mammogram',
    notes: 'Negative study',
    ageBand: '40-49',
    deviceType: 'vendor-c',
    densityCategory: 'a-fatty',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-027',
    createdAt: '2025-12-14T15:00:00Z',
    status: 'pending',
    riskScore: 47,
    confidence: 0.53,
    uncertaintyFlag: true,
    patientMaskedId: 'PT-79135',
    modality: 'tomosynthesis',
    notes: 'Unclear finding, uncertain assessment',
    ageBand: '70+',
    deviceType: 'vendor-a',
    densityCategory: 'd-dense',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-028',
    createdAt: '2025-12-13T08:00:00Z',
    status: 'finalized',
    riskScore: 31,
    confidence: 0.88,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-80246',
    modality: 'mammogram',
    notes: 'Stable benign findings',
    ageBand: '50-59',
    deviceType: 'vendor-b',
    densityCategory: 'b-scattered',
    groundTruth: 'benign',
  },
  {
    id: 'CASE-029',
    createdAt: '2025-12-13T10:00:00Z',
    status: 'pending',
    riskScore: 77,
    confidence: 0.72,
    uncertaintyFlag: false,
    patientMaskedId: 'PT-91357',
    modality: 'tomosynthesis',
    notes: 'Concerning architectural distortion',
    ageBand: '60-69',
    deviceType: 'vendor-c',
    densityCategory: 'c-heterogeneous',
    groundTruth: 'malignant',
  },
  {
    id: 'CASE-030',
    createdAt: '2025-12-13T12:00:00Z',
    status: 'needs-second-review',
    riskScore: 66,
    confidence: 0.46,
    uncertaintyFlag: true,
    patientMaskedId: 'PT-02468',
    modality: 'mammogram',
    notes: 'Equivocal finding, low confidence',
    ageBand: '40-49',
    deviceType: 'vendor-a',
    densityCategory: 'd-dense',
    groundTruth: 'benign',
  },
];

export const mockFindings: Finding[] = mockCases.map((c, idx) => ({
  id: `FIND-${String(idx + 1).padStart(3, '0')}`,
  caseId: c.id,
  regionId: `R${idx % 4 + 1}`,
  label: c.riskScore > 75 ? 'Suspicious mass' : c.riskScore > 50 ? 'Asymmetry' : 'Normal variation',
  rationaleBullets: c.riskScore > 75 
    ? [
        'Irregular margins detected',
        'Asymmetric density compared to prior',
        'Suspicious microcalcification pattern',
        'Increased vascularity in region'
      ]
    : c.riskScore > 50
    ? [
        'Focal asymmetry noted',
        'Requires comparison with prior studies',
        'No definite mass identified'
      ]
    : [
        'Normal breast parenchyma',
        'No suspicious findings',
        'Benign appearance'
      ],
  heatmapRegions: [
    {
      x: 0.3 + (idx * 0.03) % 0.4,
      y: 0.2 + (idx * 0.05) % 0.5,
      w: 0.08 + (c.riskScore / 1000),
      h: 0.08 + (c.riskScore / 1000),
      intensity: c.riskScore / 100,
    },
  ],
  severity: c.riskScore > 85 ? 'critical' : c.riskScore > 70 ? 'high' : c.riskScore > 50 ? 'moderate' : 'low',
}));

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'AUD-001',
    timestamp: '2025-12-16T10:30:00Z',
    user: 'Dr. Sarah Chen',
    caseId: 'CASE-001',
    action: 'viewed',
    details: 'Viewed case CASE-001',
  },
  {
    id: 'AUD-002',
    timestamp: '2025-12-16T10:35:00Z',
    user: 'Dr. Sarah Chen',
    caseId: 'CASE-001',
    action: 'chat-query',
    details: 'Asked AI assistant about risk factors',
  },
  {
    id: 'AUD-003',
    timestamp: '2025-12-16T10:40:00Z',
    user: 'Dr. Sarah Chen',
    caseId: 'CASE-001',
    action: 'decision-made',
    details: 'Confirmed finding as high risk',
  },
];

export const mockDecisions: Decision[] = [];

// Helper functions
export function getCaseById(id: string): Case | undefined {
  return mockCases.find(c => c.id === id);
}

export function getFindingsByCaseId(caseId: string): Finding[] {
  return mockFindings.filter(f => f.caseId === caseId);
}

export function getAuditEventsByCaseId(caseId: string): AuditEvent[] {
  return mockAuditEvents.filter(e => e.caseId === caseId);
}

export function getCaseIndex(caseId: string): number {
  return mockCases.findIndex(c => c.id === caseId);
}

export function getNextCase(currentId: string): Case | undefined {
  const idx = getCaseIndex(currentId);
  if (idx === -1 || idx === mockCases.length - 1) return undefined;
  return mockCases[idx + 1];
}

export function getPreviousCase(currentId: string): Case | undefined {
  const idx = getCaseIndex(currentId);
  if (idx <= 0) return undefined;
  return mockCases[idx - 1];
}
